### ISSUE TITLE
update fairy-stockfish nnues

### ISSUE THREAD

**Issue by Juesto** [lichess-org/lifat#30]
as per https://fairy-stockfish.github.io/nnue/ (happened some months ago this year)
the updated nnues are 3check and antichess

**Comment by niklasf** [comment]
Thanks for the heads up. Will land with the next deploy.

**Comment by Juesto** [comment]
uh @niklasf think it might be better to delete the older nnues from lifat because of how fsf selects them. but nevermind, i understood now, sorry for bothering

**Comment by niklasf** [comment]
No worries. Yeah, selection works a bit different on the web. But I set a reminder to soon clean-up the old ones.
